### ISSUE TITLE
Chars before SExprs are only parsed if the SExpr is at the top level

### ISSUE THREAD

**Issue by 0xmycf** [chiroptical/snail#9]
Hello!
Given this piece of code:

```
'(test)

(test '(inside))

#(different-char)

(different-char/2 #(inside))
```

I'll show the third and fourth expr as examples:
```txt
SExpression (Just '#') Round [Lexeme (SourcePos {...},"different-char")]

SExpression Nothing Round [
                 Lexeme (SourcePos {...},"different-char/2"),Lexeme (SourcePos {...},"#") <--------------- here

                       Shouldnt it be (Just '#')?                             <--------------- and here
                             vvvvvvv
               , SExpression Nothing Round [Lexeme (SourcePos {...},"inside")]]
```

I think this is because `leaves` tries `lexeme` before it tries `sExpression`

```hs
leaves :: Parser SnailAst
leaves = lexeme <|> textLiteral <|> sExpression
```

I switched this around in a local clone:

```hs
leaves :: Parser SnailAst
leaves = try sExpression <|> lexeme <|> textLiteral 
```

This needs a `try` though (imagine something like `@,(foo ...)`.

But with this change I get:

```txt
SExpression (Just '#') Round [Lexeme (SourcePos {...},"different-char")]
                                                                                       vvvvvv
SExpression Nothing Round [Lexeme (SourcePos  {...},"different-char/2"),SExpression (Just '#') Round [Lexeme (SourcePos {...},"inside")]]
```

Which is what I had expected.

I am not super familiar with the grammar of LISP and its dialects, so maybe this is intended.

Thank you for creating this though, its gonna be super handy for me in the future!

**Comment by chiroptical** [comment]
Nice find! Let me get a test in place and try your suggestion.

**Comment by chiroptical** [comment]
Yeah, I think you are on to something for sure. My biggest concern is that this will break other stuff but let's see how the test turns out. It is possible that I should just not allow `#` to lead lexemes.

As for `@,(foo ...)` I am also kind of curious how this parses. I can't recall if `@,` is a valid lexeme in snail. It only supports a single leading character for s-expressions for sure.

**Comment by 0xmycf** [comment]
Yes I can see the issue with this. I think this is fine. 

The leading double char thing is a bit weird, but probably ok. It would require a bit of a rewrite here and there and probably overcomplicate things. 
How it works now is how I would have expected it to work! 

This is not really related to this issue, but when setting up a project for testing I saw that snail is marked as broken on nixpkgs. Not sure if thats something you can do anything about. 

Thank you for the fast response!

**Comment by chiroptical** [comment]
> This is not really related to this issue, but when setting up a project for testing I saw that snail is marked as broken on nixpkgs. Not sure if thats something you can do anything about.

Do you mind opening up a ticket for this actually? I am unsure how easy it is to fix that.
